jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: samueldr/lix-gha-installer-action@7b7f14d320d6aacfb65bd1ef761566b3b69e474c # main
    - name: Build package
      run: nix-build ./nix -A package -I nixpkgs=channel:nixos-unstable
    - name: Build tests
      run: nix-build ./nix -A tests -I nixpkgs=channel:nixos-unstable
name: '[Portail] Run test suite'
on:
  pull_request:
  push:
    branches:
    - main
