jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - uses: samueldr/lix-gha-installer-action@7b7f14d320d6aacfb65bd1ef761566b3b69e474c # main
    - name: Build package
      run: nix-build ./nix -A package -I nixpkgs=channel:nixos-unstable
    - name: Build tests
      run: nix-build ./nix -A tests -I nixpkgs=channel:nixos-unstable
name: '[Portail] Run test suite'
on:
  pull_request:
  push:
    branches:
    - main
